### ISSUE TITLE
Try to got unique id concurrently

### ISSUE THREAD

**Issue by jiamo** [godruoyi/go-snowflake#4]
```
package tests

import (
	"fmt"
	mapset "github.com/deckarep/golang-set/v2"
	"testing"
)

func TestCache(t *testing.T) {
	ids := mapset.NewSet[uint64]()
	for i := 1; i <= 10000; i++ {
		go func() {
			id, _ := snowflake.NextID()
			if ids.Contains(id) {
				fmt.Printf("repeat id %d", id)
			}

			ids.Add(id)
		}()

	}

	fmt.Printf("%v \n", ids.Cardinality())

}

```
try to concurrently  to got unique id by such example. Always got  such like
```
6335
```

Do you have some suggestions try to make this test case got 
```
10000 
```

**Comment by godruoyi** [comment]
Thank you @jiamo, but I don't have details knowledge about the declares/golang-set, could you please add some sleep near the fmt.Print line?

**Comment by jiamo** [comment]
change to 
```
			id, _ := snowflake.NextID()
			//if ids.Contains(id) {
			//	fmt.Printf("repeat id %d", id)
			//}
			time.Sleep(time.Millisecond)
			ids.Add(id)
```
is the same result.

**Comment by jiamo** [comment]
And try to and atomic such like 
```
var lastId uint64

func NextID() (uint64, error) {
	var last uint64
	for {
		last = atomic.LoadUint64(&lastId)
		c := currentMillis()
		seqResolver := callSequenceResolver()
		seq, err := seqResolver(c)

		if err != nil {
			//return 0, err
			continue
		}

		for seq >= MaxSequence {
			c = waitForNextMillis(c)
			seq, err = seqResolver(c)
			if err != nil {
				//return 0, err
				continue
			}
		}

		df := elapsedTime(c, startTime)
		//if df < 0 || uint64(df) > MaxTimestamp {
		//	return 0, errors.New("the maximum life cycle of the snowflake algorithm is 2^41-1(millis), please check start-time")
		//}

		id := (uint64(df) << uint64(timestampMoveLength)) | (machineID << uint64(machineIDMoveLength)) | uint64(seq)
		if atomic.CompareAndSwapUint64(&lastId, last, id) {
			return id, nil
		}
	}
}
```
It still can't get to `10000`.

**Comment by godruoyi** [comment]
Hi, @jiamo I think the problem is caused by the declares/golang-set, we need to know the map is not concurrent security, may you can check the test case here to get more detail.

https://github.com/godruoyi/go-snowflake/blob/master/snowflake_test.go#L34-L60

**Comment by jiamo** [comment]
`TestID_bitch` is ok.  I need check more on the  `declares/golang-set.`  The real problem met come from   using your repo to test https://fly.io/dist-sys/2/  The problem is same here.

**Comment by jiamo** [comment]
change to 
```
func TestCache(t *testing.T) {
	ids := mapset.NewSet[uint64]()
	var wg sync.WaitGroup
	for i := 1; i <= 10000; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			id, _ := internal.NextID()
			ids.Add(id)
		}()

	}
	min, max := MinMax(ids.ToSlice())
	wg.Wait()
	fmt.Printf("%v %v %v\n", ids.Cardinality(), min, max)
}
```
Is ok too. The `wg` usage has such effect to make all id unique ? While the problem from "https://fly.io/dist-sys/2/" is much like the original one without having WaitGroup to control the handling goroutines.

**Comment by godruoyi** [comment]
hi, @jiamo it looks like works fine for me, could you please try again, may we need to wait for all the goroutine to finish first.
<img width="859" alt="image" src="https://user-images.githubusercontent.com/16079222/221523342-45af592e-82a2-4903-b686-bfd8584c8b15.png">

**Comment by jiamo** [comment]
Thanks. I got it . You are right.  There is no problem. I will dig more on "https://fly.io/dist-sys/2/" which  their test case can't pass . Maybe is not snowflake problem.

**Comment by godruoyi** [comment]
Enjoy your time.
